param([Parameter(Mandatory=$true)][string]$PackageRoot)
$ErrorActionPreference = 'Stop'
$taskAsar = Get-Item -LiteralPath (Join-Path $PackageRoot 'app\resources\app.asar')
$taskAdapterPath = Join-Path $PSScriptRoot 'adapter.json'
$taskPackageName = Split-Path $PackageRoot -Leaf
# Reuse only an adapter generated by this scanner for the exact installed resource.
if (Test-Path -LiteralPath $taskAdapterPath) {
 try {
  $taskCached = Get-Content -LiteralPath $taskAdapterPath -Raw | ConvertFrom-Json
  if ($taskCached.scannerVersion -eq 3 -and $taskCached.testedPackage -eq $taskPackageName -and $taskCached.asarSize -eq $taskAsar.Length -and $taskCached.asarModifiedUtc -eq $taskAsar.LastWriteTimeUtc.Ticks -and $taskCached.clientCandidates.Count -gt 0) { return }
 } catch { }
}
$taskStream = [IO.File]::OpenRead($taskAsar.FullName)
$taskReader = New-Object IO.BinaryReader($taskStream)
try {
 [void]$taskReader.ReadUInt32(); $taskHeaderSize=$taskReader.ReadUInt32(); [void]$taskReader.ReadUInt32(); $taskJsonSize=$taskReader.ReadUInt32()
 if($taskJsonSize -gt 16777216){throw 'Unexpected ASAR header size'}
 $taskHeader=[Text.Encoding]::UTF8.GetString($taskReader.ReadBytes([int]$taskJsonSize)) | ConvertFrom-Json
 $taskBase=8+$taskHeaderSize; $taskAssets=$taskHeader.files.webview.files.assets.files
 $taskProbes=@(); $taskClients=@()
 foreach($taskFile in @($taskAssets.PSObject.Properties | Where-Object {$_.Name -like 'about-you-summary-*.js'})) {
  $taskStream.Position=$taskBase+[long]$taskFile.Value.offset
  $taskSource=[Text.Encoding]::UTF8.GetString($taskReader.ReadBytes([int]$taskFile.Value.size))
  $taskCalls=[regex]::Matches($taskSource,'(?<alias>[$A-Za-z_][\w$]*)\.safeGet\(\s*[`"]\/conversation\/\{conversation_id\}')
  if($taskCalls.Count -eq 0){continue}
  $taskProbes += './assets/'+$taskFile.Name
  foreach($taskImport in [regex]::Matches($taskSource,'import\{([^}]+)\}from"(\./app-shared-[a-f0-9]+\.js)"')) {
   foreach($taskCall in $taskCalls){
    foreach($taskBinding in $taskImport.Groups[1].Value.Split(',')){
     $taskPair=[regex]::Match($taskBinding.Trim(),'^(?<export>[\w$]+)(?:\s+as\s+(?<local>[\w$]+))?$')
     if(!$taskPair.Success){continue}
     $taskAlias=if($taskPair.Groups['local'].Success){$taskPair.Groups['local'].Value}else{$taskPair.Groups['export'].Value}
     if($taskAlias -eq $taskCall.Groups['alias'].Value){$taskClients += [pscustomobject]@{module='./assets/'+$taskImport.Groups[2].Value.Substring(2);export=$taskPair.Groups['export'].Value;score=[regex]::Matches($taskSource,('\b'+[regex]::Escape($taskAlias)+'\.safeGet\(')).Count}}
    }
   }
  }
 }
 $taskClients=@($taskClients | Sort-Object -Property @{Expression='score';Descending=$true} | Group-Object module,export | ForEach-Object {$_.Group[0]} | Sort-Object -Property @{Expression='score';Descending=$true} | Select-Object module,export)
 if($taskClients.Count -eq 0){throw 'No semantic conversation history client found'}
 $taskResult=[ordered]@{schema=2;scannerVersion=3;asarSize=$taskAsar.Length;asarModifiedUtc=$taskAsar.LastWriteTimeUtc.Ticks;module=$taskClients[0].module;export=$taskClients[0].export;clientCandidates=$taskClients;clientProbes=$taskProbes;testedPackage=$taskPackageName;source='semantic conversation history call; no fixed minifier alias'}
 foreach($taskFile in @($taskAssets.PSObject.Properties | Where-Object {$_.Name -like 'chatgpt-conversation-page-*.js' -and $_.Value.size -gt 10000})){
  $taskStream.Position=$taskBase+[long]$taskFile.Value.offset
  $taskSource=[Text.Encoding]::UTF8.GetString($taskReader.ReadBytes([int]$taskFile.Value.size))
  $taskImport=[regex]::Match($taskSource,'import\{([^}]+)\}from"\./controller-[a-f0-9]+\.js"')
  $taskAlias=[regex]::Match($taskImport.Groups[1].Value,'(?:^|,)\s*t as ([\w$]+)(?:,|$)')
  if($taskAlias.Success){$taskResult.historyLoaderPattern='\bawait\s+'+[regex]::Escape($taskAlias.Groups[1].Value)+'\(';break}
 }
 $taskResult | ConvertTo-Json -Depth 5 -Compress | Set-Content -LiteralPath (Join-Path $PSScriptRoot 'adapter.json') -Encoding UTF8
}finally{$taskReader.Dispose();$taskStream.Dispose()}
